map_type: costmap
transform_tolerance: 0.2
obstacle_range: 0.40
raytrace_range: 2.5
footprint: [[0.33, 0.32], [0.33, -0.32], [-0.33, -0.32], [-0.33, 0.32]]
inflation_radius: 0.3
observation_sources: laser_scan
laser_scan:
  sensor_frame: base_link
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true

