global_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  width: 50
  height: 50
  resolution: 0.05
  static_map: true
  rolling_window: false
