image: /home/tas_group_06/catkin_ws/src/tas/tas/launch/config/map_server/hectormap.pgm
resolution: 0.010000
origin: [-30.004999, -30.004999, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

